# ex_compile: ex_compile.c
# 	gcc `pkg-config --cflags glib-2.0` -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -lglib-2.0 -o ex_compile ex_compile.c `pkg-config --libs glib-2.0`
	
word_count: word_count.c
	gcc `pkg-config --cflags glib-2.0` -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -lglib-2.0 -o word_count word_count.c `pkg-config --libs glib-2.0`